Repository hanghae-skillup/redis_1st, pull requests merged in 2025-01, with the labels that each got.

#17 [1주차] 멀티모듈 구성 및 요구사항 구현
  README.md
  cinema/.gitattributes
  cinema/.gitignore
  cinema/adapter/build.gradle
  cinema/adapter/persistence/build.gradle
  cinema/adapter/persistence/src/main/java/com/hanghae/cinema/adapter/persistence/MoviePersistenceAdapter.java
  cinema/adapter/persistence/src/main/java/com/hanghae/cinema/adapter/persistence/config/JpaConfig.java
  cinema/adapter/persistence/src/main/java/com/hanghae/cinema/adapter/persistence/config/PersistenceConfig.java
  cinema/adapter/persistence/src/main/java/com/hanghae/cinema/adapter/persistence/entity/BaseEntity.java
  cinema/adapter/persistence/src/main/java/com/hanghae/cinema/adapter/persistence/entity/MovieEntity.java
  cinema/adapter/persistence/src/main/java/com/hanghae/cinema/adapter/persistence/entity/ShowTimeEntity.java
  cinema/adapter/persistence/src/main/java/com/hanghae/cinema/adapter/persistence/entity/TheaterEntity.java
  cinema/adapter/persistence/src/main/java/com/hanghae/cinema/adapter/persistence/mapper/MovieEntityMapper.java
  cinema/adapter/persistence/src/main/java/com/hanghae/cinema/adapter/persistence/repository/MovieRepository.java
  cinema/adapter/web/build.gradle
  cinema/adapter/web/src/main/java/com/hanghae/cinema/adapter/web/controller/MovieController.java
  cinema/api/build.gradle
  cinema/api/src/main/java/com/hanghae/cinema/ApiApplication.java
  cinema/api/src/main/java/com/hanghae/cinema/config/ApiConfig.java
  cinema/api/src/main/resources/application.yml
  cinema/application/build.gradle
  cinema/application/src/main/java/com/hanghae/cinema/application/config/ApplicationConfig.java
  cinema/application/src/main/java/com/hanghae/cinema/application/dto/MovieResponseDTO.java
  cinema/application/src/main/java/com/hanghae/cinema/application/mapper/MovieMapper.java
  cinema/application/src/main/java/com/hanghae/cinema/application/port/FindMoviePort.java
  cinema/application/src/main/java/com/hanghae/cinema/application/service/MovieService.java
  cinema/application/src/main/java/com/hanghae/cinema/application/usecase/FindMovieUseCase.java
  cinema/build.gradle
  cinema/docker-compose.yml
  cinema/domain/build.gradle
  cinema/domain/src/main/java/com/hanghae/cinema/domain/model/Movie.java
  cinema/domain/src/main/java/com/hanghae/cinema/domain/model/Showtime.java
  cinema/domain/src/main/java/com/hanghae/cinema/domain/model/Theater.java
  cinema/domain/src/main/java/com/hanghae/cinema/domain/type/MovieGenre.java
  cinema/domain/src/main/java/com/hanghae/cinema/domain/type/MovieRating.java
  cinema/gradle/wrapper/gradle-wrapper.jar
  cinema/gradle/wrapper/gradle-wrapper.properties
  cinema/gradlew
  cinema/gradlew.bat
  cinema/settings.gradle
  cinema/src/main/java/com/hanghae/cinema/CinemaApplication.java
  cinema/src/main/resources/application.properties
  cinema/src/test/java/com/hanghae/cinema/CinemaApplicationTests.java
Labels: 1주차

#21 [1주차] 멀티모듈 구성 및 영화목록 조회 API 개발
  .gitignore
  README.md
  adapter/build.gradle
  adapter/src/main/java/com/hanghae/adapter/controller/MovieController.java
  adapter/src/main/java/hhCinema/HhCinemaApplication.java
  adapter/src/test/resources/movie-api-test.http
  application/build.gradle
  application/src/main/java/com/hanghae/application/service/MovieService.java
  application/src/main/java/com/hanghae/application/service/exception/MovieNotFoundException.java
  build.gradle
  common/build.gradle
  common/src/main/java/com/hanghae/common/dto/MovieResponseDto.java
  docker-compose.yml
  domain/build.gradle
  domain/src/main/java/com/hanghae/domain/entity/BaseEntity.java
  domain/src/main/java/com/hanghae/domain/entity/Genre.java
  domain/src/main/java/com/hanghae/domain/entity/Movie.java
  domain/src/main/java/com/hanghae/domain/entity/Reservation.java
  domain/src/main/java/com/hanghae/domain/entity/Seat.java
  domain/src/main/java/com/hanghae/domain/entity/Showtime.java
  domain/src/main/java/com/hanghae/domain/entity/Theater.java
  domain/src/main/java/com/hanghae/domain/entity/User.java
  domain/src/main/java/com/hanghae/domain/repository/MovieRepository.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  infrastructure/build.gradle
  infrastructure/src/main/java/com/hanghae/infrastructure/config/DatabaseConfig.java
  infrastructure/src/main/resources/application.yml
  settings.gradle
  sql-scripts/hhCinema_ddl.sql
  sql-scripts/hhCinema_init_data.sql
  sql-scripts/hhCinema_init_showtime.sql
Labels: 1주차

#49 [2주차] 검색 및 필터링 개발 및 인덱스, 캐싱 적용
  .gitattributes
  .gitignore
  README.md
  build.gradle
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  init-scripts/data.sql
  k6-test/test.js
  module-api/build.gradle
  module-api/src/main/java/hellojpa/Main.java
  module-api/src/main/java/hellojpa/controller/ScreeningController.java
  module-api/src/main/resources/application.yml
  module-api/src/test/resources/http/api-test.http
  module-common/build.gradle
  module-common/src/main/java/hellojpa/BaseEntity.java
  module-common/src/main/java/hellojpa/Main.java
  module-common/src/main/java/hellojpa/config/CacheConfig.java
  module-common/src/main/java/hellojpa/config/JacksonConfig.java
  module-common/src/main/java/hellojpa/config/QuerydslConfig.java
  module-common/src/main/java/hellojpa/config/RedisConfig.java
  module-common/src/main/java/hellojpa/config/RedissonConfig.java
  module-common/src/main/java/hellojpa/exception/GlobalExceptionHandler.java
  module-movie/build.gradle
  module-movie/src/main/java/hellojpa/Main.java
  module-movie/src/main/java/hellojpa/domain/Genre.java
  module-movie/src/main/java/hellojpa/domain/Movie.java
  module-movie/src/main/java/hellojpa/domain/VideoRating.java
  module-screening/build.gradle
  module-screening/src/main/java/hellojpa/Main.java
  module-screening/src/main/java/hellojpa/domain/Screening.java
  module-screening/src/main/java/hellojpa/dto/ScreeningDto.java
  module-screening/src/main/java/hellojpa/dto/SearchCondition.java
  module-screening/src/main/java/hellojpa/dto/TheaterScheduleDto.java
  module-screening/src/main/java/hellojpa/dto/TimeScheduleDto.java
  module-screening/src/main/java/hellojpa/repository/ScreeningRepository.java
  module-screening/src/main/java/hellojpa/repository/ScreeningRepositoryCustom.java
  module-screening/src/main/java/hellojpa/repository/ScreeningRepositoryImpl.java
  module-screening/src/main/java/hellojpa/service/ScreeningService.java
  module-theater/build.gradle
  module-theater/src/main/java/hellojpa/Main.java
  module-theater/src/main/java/hellojpa/domain/Seat.java
  module-theater/src/main/java/hellojpa/domain/Theater.java
  settings.gradle
Labels: 2주차

#47 [2주차] API 검색 기능 추가, Redis 캐싱, 성능 테스트
  .gitattributes
  .gitignore
  Dockerfile
  README.md
  build.gradle
  cinema-adapter/build.gradle
  cinema-adapter/src/main/java/com/cinema/CinemaApplication.java
  cinema-adapter/src/main/java/com/cinema/adapter/config/WebConfig.java
  cinema-adapter/src/main/java/com/cinema/adapter/controller/MovieController.java
  cinema-adapter/src/main/java/com/cinema/adapter/filter/Utf8EncodingFilter.java
  cinema-adapter/src/main/resources/application.yml
  cinema-application/build.gradle
  cinema-application/src/main/java/com/cinema/Main.java
  cinema-application/src/main/java/com/cinema/application/dto/MovieResponseDTO.java
  cinema-application/src/main/java/com/cinema/application/mapper/MovieMapper.java
  cinema-application/src/main/java/com/cinema/application/service/MovieService.java
  cinema-common/build.gradle
  cinema-common/src/main/java/com/cinema/Main.java
  cinema-common/src/main/java/com/cinema/common/enums/GenreCode.java
  cinema-common/src/main/java/com/cinema/common/enums/GradeCode.java
  cinema-common/src/main/java/com/cinema/common/enums/SeatTypeCode.java
  cinema-core/build.gradle
  cinema-core/src/main/java/com/cinema/Main.java
  cinema-core/src/main/java/com/cinema/core/domain/BaseEntity.java
  cinema-core/src/main/java/com/cinema/core/domain/Movie.java
  cinema-core/src/main/java/com/cinema/core/domain/Screening.java
  cinema-core/src/main/java/com/cinema/core/domain/Seat.java
  cinema-core/src/main/java/com/cinema/core/domain/Theater.java
  cinema-core/src/main/java/com/cinema/core/domain/Ticket.java
  cinema-core/src/main/java/com/cinema/core/domain/User.java
  cinema-infra/build.gradle
  cinema-infra/src/main/java/com/cinema/Main.java
  cinema-infra/src/main/java/com/cinema/infra/config/RedisConfig.java
  cinema-infra/src/main/java/com/cinema/infra/dto/MovieScreeningData.java
  cinema-infra/src/main/java/com/cinema/infra/dto/ScreeningData.java
  cinema-infra/src/main/java/com/cinema/infra/repository/MovieRepository.java
  compose.yaml
  ddl.sql
  ddl_no_index.sql
  docs/images/corrected_erd.png
  docs/images/erd.png
  docs/images/k6_01_1_redis_noindex.png
  docs/images/k6_01_2_redis_noindex.png
  docs/images/k6_02_1_redis_index.png
  docs/images/k6_02_2_redis_index.png
  docs/images/problem3-1.jpg
  docs/images/problem3-2.jpg
  docs/images/problem4-1.png
  docs/images/problem4-2.png
  docs/images/problem4-3.png
  docs/images/problem5-1.png
  dummy_data.sql
  dummy_data_movie.sql
  dummy_data_screening.sql
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/resources/http/cinema.http
Labels: 2주차

#56 [2주차] 데이터 검색 / 필터 / 캐싱
  cinema/.gitattributes
  cinema/.gitignore
  cinema/ReadMe.md
  cinema/build.gradle.kts
  cinema/cinema-admin/build.gradle.kts
  cinema/cinema-admin/src/main/java/com/study/cinema/CinemaAdminApplication.java
  cinema/cinema-admin/src/main/resources/application.yaml
  cinema/cinema-admin/src/test/java/com/study/cinema/CinemaAdminApplicationTests.java
  cinema/cinema-api/build.gradle.kts
  cinema/cinema-api/src/main/kotlin/com/study/cinema/CinemaApiApplication.kt
  cinema/cinema-api/src/main/kotlin/com/study/cinema/application/CinemaScheduleFacade.kt
  cinema/cinema-api/src/main/kotlin/com/study/cinema/interface/CinemaV1Controller.kt
  cinema/cinema-api/src/main/kotlin/com/study/cinema/interface/CinemaV1Dto.kt
  cinema/cinema-api/src/main/resources/application.yaml
  cinema/cinema-api/src/main/resources/data.sql
  cinema/cinema-api/src/main/resources/index.sql
  cinema/cinema-api/src/main/resources/schema.sql
  cinema/cinema-api/src/test/kotlin/com/study/cinema/CinemaApiApplicationTests.kt
  cinema/cinema-api/src/test/kotlin/k6/script.js
  cinema/cinema-domain/build.gradle.kts
  cinema/cinema-domain/src/main/kotlin/com/study/cinema/DummyDataLoader.kt
  cinema/cinema-domain/src/main/kotlin/com/study/cinema/domain/cinema/Cinema.kt
  cinema/cinema-domain/src/main/kotlin/com/study/cinema/domain/movie/Genre.kt
  cinema/cinema-domain/src/main/kotlin/com/study/cinema/domain/movie/Movie.kt
  cinema/cinema-domain/src/main/kotlin/com/study/cinema/domain/movie/MovieInfo.kt
  cinema/cinema-domain/src/main/kotlin/com/study/cinema/domain/movie/MovieRating.kt
  cinema/cinema-domain/src/main/kotlin/com/study/cinema/domain/schedule/MovieSchedule.kt
  cinema/cinema-domain/src/main/kotlin/com/study/cinema/domain/schedule/MovieScheduleQueryService.kt
  cinema/cinema-domain/src/main/kotlin/com/study/cinema/domain/seat/Seat.kt
  cinema/cinema-domain/src/main/kotlin/com/study/cinema/domain/theater/Theater.kt
  cinema/cinema-domain/src/main/kotlin/com/study/cinema/infra/cache/CacheConfig.kt
  cinema/cinema-domain/src/main/kotlin/com/study/cinema/infra/jpa/CustomerHibernate5Templates.kt
  cinema/cinema-domain/src/main/kotlin/com/study/cinema/infra/jpa/QueryDslConfig.kt
  cinema/cinema-domain/src/main/kotlin/com/study/cinema/infra/jpa/movie/CinemaRepository.kt
  cinema/cinema-domain/src/main/kotlin/com/study/cinema/infra/jpa/movie/MovieRepository.kt
  cinema/cinema-domain/src/main/kotlin/com/study/cinema/infra/jpa/movie/MovieScheduleRepository.kt
  cinema/cinema-domain/src/main/kotlin/com/study/cinema/infra/jpa/movie/MovieScheduleRepositoryCustom.kt
  cinema/cinema-domain/src/main/kotlin/com/study/cinema/infra/jpa/movie/MovieScheduleRepositoryCustomImpl.kt
  cinema/cinema-domain/src/main/kotlin/com/study/cinema/infra/jpa/movie/TheaterRepository.kt
  cinema/cinema-domain/src/main/kotlin/com/study/cinema/infra/redis/RedisConfig.kt
  cinema/cinema-domain/src/main/resources/application.yaml
  cinema/cinema-domain/src/test/kotlin/com/study/cinema/CinemaDomainApplicationTests.kt
  cinema/compose.yaml
  cinema/gradle/wrapper/gradle-wrapper.jar
  cinema/gradle/wrapper/gradle-wrapper.properties
  cinema/gradlew
  cinema/gradlew.bat
  cinema/http/movie.http
  cinema/settings.gradle.kts
Labels: 2주차

#46 [2주차] 리팩토링 및 검색 기능 추가
  README.md
  cinema/adapter/build.gradle
  cinema/adapter/persistence/build.gradle
  cinema/adapter/persistence/src/main/java/com/hanghae/cinema/adapter/persistence/MoviePersistenceAdapter.java
  cinema/adapter/persistence/src/main/java/com/hanghae/cinema/adapter/persistence/config/JpaConfig.java
  cinema/adapter/persistence/src/main/java/com/hanghae/cinema/adapter/persistence/entity/BaseEntity.java
  cinema/adapter/persistence/src/main/java/com/hanghae/cinema/adapter/persistence/entity/MovieEntity.java
  cinema/adapter/persistence/src/main/java/com/hanghae/cinema/adapter/persistence/entity/ShowTimeEntity.java
  cinema/adapter/persistence/src/main/java/com/hanghae/cinema/adapter/persistence/entity/TheaterEntity.java
  cinema/adapter/persistence/src/main/java/com/hanghae/cinema/adapter/persistence/mapper/MovieEntityMapper.java
  cinema/adapter/persistence/src/main/java/com/hanghae/cinema/adapter/persistence/repository/MovieRepository.java
  cinema/adapter/persistence/src/main/java/com/hanghae/cinema/adapter/persistence/repository/MovieRepositoryCustom.java
  cinema/adapter/persistence/src/main/java/com/hanghae/cinema/adapter/persistence/repository/MovieRepositoryCustomImpl.java
  cinema/adapter/web/build.gradle
  cinema/adapter/web/src/main/java/com/hanghae/cinema/adapter/ApiApplication.java
  cinema/adapter/web/src/main/java/com/hanghae/cinema/adapter/ApiConfig.java
  cinema/adapter/web/src/main/java/com/hanghae/cinema/adapter/web/controller/MovieController.java
  cinema/adapter/web/src/main/resources/application.yml
  cinema/api/build.gradle
  cinema/application/build.gradle
  cinema/application/src/main/java/com/hanghae/cinema/application/CacheType.java
  cinema/application/src/main/java/com/hanghae/cinema/application/config/CacheConfig.java
  cinema/application/src/main/java/com/hanghae/cinema/application/dto/MovieResponseDTO.java
  cinema/application/src/main/java/com/hanghae/cinema/application/dto/ShowTimeResponseDTO.java
  cinema/application/src/main/java/com/hanghae/cinema/application/dto/TheaterResponseDTO.java
  cinema/application/src/main/java/com/hanghae/cinema/application/mapper/MovieMapper.java
  cinema/application/src/main/java/com/hanghae/cinema/application/port/FindMoviePort.java
  cinema/application/src/main/java/com/hanghae/cinema/application/service/MovieService.java
  cinema/application/src/main/java/com/hanghae/cinema/application/usecase/FindMovieUseCase.java
  cinema/build.gradle
  cinema/docker-compose.yml
  cinema/domain/src/main/java/com/hanghae/cinema/domain/model/Movie.java
  cinema/domain/src/main/java/com/hanghae/cinema/domain/model/ShowTime.java
  cinema/domain/src/main/java/com/hanghae/cinema/domain/model/Theater.java
  cinema/http/get_movies.http
  cinema/http/get_movies_filter.http
  cinema/http/get_movies_keyword.http
  cinema/settings.gradle
  cinema/src/main/java/com/hanghae/cinema/CinemaApplication.java
  cinema/src/main/resources/application.properties
  cinema/src/test/java/com/hanghae/cinema/CinemaApplicationTests.java
Labels: 2주차

#43 [2주차] 검색기능 추가, 캐시 적용 및 성능 테스트
  .gitignore
  README.md
  app/.gitattributes
  app/.gitignore
  app/build.gradle
  app/compose.yaml
  app/gradle/wrapper/gradle-wrapper.jar
  app/gradle/wrapper/gradle-wrapper.properties
  app/gradlew
  app/gradlew.bat
  app/settings.gradle
  app/src/main/java/com/movie/app/AppApplication.java
  app/src/main/java/com/movie/app/config/RedisCacheConfig.java
  app/src/main/java/com/movie/app/controller/MovieRestController.java
  app/src/main/java/com/movie/app/domain/Movie.java
  app/src/main/java/com/movie/app/domain/MovieRepository.java
  app/src/main/java/com/movie/app/domain/MovieRequestDto.java
  app/src/main/java/com/movie/app/domain/Timestamped.java
  app/src/main/java/com/movie/app/service/MovieService.java
  app/src/main/resources/application.properties
  app/src/main/resources/static/basic.js
  app/src/main/resources/static/images/icon-search.png
  app/src/main/resources/static/index.html
  app/src/main/resources/static/style.css
  app/src/test/java/com/movie/app/AppApplicationTests.java
  document/perfomanceResult_after_250119
  document/perfomanceResult_before_250119.txt
  document/perfomance_test_with_redis.md
  document/scenario.md
  tools/k6/script.ts
  tools/mysql/init.sql
Labels: 2주차

#60 [2주차] 검색 / 인덱싱 / 캐시 적용
  Dockerfile
  README.md
  api/src/main/kotlin/io/github/jehwanyoo/redis_1st/v1/BaseApiV1Controller.kt
  api/src/main/kotlin/io/github/jehwanyoo/redis_1st/v1/movies/MovieController.http
  api/src/main/kotlin/io/github/jehwanyoo/redis_1st/v1/movies/MovieController.kt
  api/src/main/kotlin/io/github/jehwanyoo/redis_1st/v1/movies/MovieResponse.kt
  api/src/main/resources/application.properties
  application/build.gradle.kts
  application/src/main/kotlin/io/github/jehwanyoo/redis_1st/aggregate/MovieDetail.kt
  application/src/main/kotlin/io/github/jehwanyoo/redis_1st/repository/port/MovieRepository.kt
  application/src/main/kotlin/io/github/jehwanyoo/redis_1st/use_case/GetMovieDetailsUseCase.kt
  application/src/main/kotlin/io/github/jehwanyoo/redis_1st/usecase/port/GetMoviesByTitleContainingUseCase.kt
  application/src/main/kotlin/io/github/jehwanyoo/redis_1st/usecase/port/GetMoviesUseCase.kt
  application/src/main/kotlin/io/github/jehwanyoo/redis_1st/usecase/service/GetMovieUseCaseImpl.kt
  application/src/main/kotlin/io/github/jehwanyoo/redis_1st/usecase/service/GetMoviesByTitleContainingUseCaseImpl.kt
  core/build.gradle.kts
  core/src/main/kotlin/io/github/jehwanyoo/redis_1st/Application.kt
  docker-compose.yml
  domain/build.gradle.kts
  domain/src/main/kotlin/io/github/jehwanyoo/redis_1st/entity/Screen.kt
  domain/src/main/kotlin/io/github/jehwanyoo/redis_1st/model/Movie.kt
  domain/src/main/kotlin/io/github/jehwanyoo/redis_1st/model/Screen.kt
  domain/src/main/kotlin/io/github/jehwanyoo/redis_1st/model/ShowTime.kt
  domain/src/main/kotlin/io/github/jehwanyoo/redis_1st/repository/MovieRepository.kt
  infrastructure/build.gradle.kts
  infrastructure/src/main/kotlin/io/github/jehwanyoo/redis_1st/cache/CacheConfig.kt
  infrastructure/src/main/kotlin/io/github/jehwanyoo/redis_1st/entity/DbMovie.kt
  infrastructure/src/main/kotlin/io/github/jehwanyoo/redis_1st/repository/MovieRepositoryImpl.kt
  infrastructure/src/main/kotlin/io/github/jehwanyoo/redis_1st/repository/adpater/MovieRepositoryImpl.kt
  infrastructure/src/main/kotlin/io/github/jehwanyoo/redis_1st/repository/entity/MovieEntity.kt
  infrastructure/src/main/kotlin/io/github/jehwanyoo/redis_1st/repository/entity/ScreenEntity.kt
  infrastructure/src/main/kotlin/io/github/jehwanyoo/redis_1st/repository/entity/ShowTimeEntity.kt
  infrastructure/src/main/kotlin/io/github/jehwanyoo/redis_1st/repository/seeder/DataSeeder.kt
  infrastructure/src/main/resources/application.yml
  infrastructure/src/main/resources/data.sql
  performance_test/with_title.js
  performance_test/without_title.js
  settings.gradle.kts
Labels: 2주차

#72 [3주차] 예매 API 구현, Lock 적용
  README.md
  build.gradle
  cinema-adapter/build.gradle
  cinema-adapter/src/main/java/com/cinema/CinemaApplication.java
  cinema-adapter/src/main/java/com/cinema/adapter/controller/MovieController.java
  cinema-adapter/src/main/java/com/cinema/adapter/controller/TicketController.java
  cinema-adapter/src/main/resources/application.yml
  cinema-adapter/src/test/java/com/cinema/PessimisticLockTest.java
  cinema-application/build.gradle
  cinema-application/src/main/java/com/cinema/application/dto/MovieRequestDTO.java
  cinema-application/src/main/java/com/cinema/application/dto/MovieResponseDTO.java
  cinema-application/src/main/java/com/cinema/application/dto/TicketRequestDTO.java
  cinema-application/src/main/java/com/cinema/application/mapper/MovieMapper.java
  cinema-application/src/main/java/com/cinema/application/service/MovieService.java
  cinema-application/src/main/java/com/cinema/application/service/TicketService.java
  cinema-common/src/main/java/com/cinema/common/enums/SeatNameCode.java
  cinema-common/src/main/java/com/cinema/common/exception/GlobalExceptionHandler.java
  cinema-core/build.gradle
  cinema-core/src/main/java/com/cinema/core/annotation/DistributedLock.java
  cinema-core/src/main/java/com/cinema/core/domain/BaseEntity.java
  cinema-core/src/main/java/com/cinema/core/domain/Movie.java
  cinema-core/src/main/java/com/cinema/core/domain/Screening.java
  cinema-core/src/main/java/com/cinema/core/domain/Seat.java
  cinema-core/src/main/java/com/cinema/core/domain/Ticket.java
  cinema-core/src/main/java/com/cinema/core/domain/TicketSeat.java
  cinema-infra/build.gradle
  cinema-infra/src/main/java/com/cinema/infra/config/DistributedLockAspect.java
  cinema-infra/src/main/java/com/cinema/infra/config/QueryDslConfig.java
  cinema-infra/src/main/java/com/cinema/infra/config/RedissonConfig.java
  cinema-infra/src/main/java/com/cinema/infra/config/TransactionConfig.java
  cinema-infra/src/main/java/com/cinema/infra/dto/MovieScreeningData.java
  cinema-infra/src/main/java/com/cinema/infra/lock/DistributedLockUtil.java
  cinema-infra/src/main/java/com/cinema/infra/repository/MovieRepository.java
  cinema-infra/src/main/java/com/cinema/infra/repository/MovieRepositoryCustom.java
  cinema-infra/src/main/java/com/cinema/infra/repository/MovieRepositoryCustomImpl.java
  cinema-infra/src/main/java/com/cinema/infra/repository/SeatRepository.java
  cinema-infra/src/main/java/com/cinema/infra/repository/TicketRepository.java
  cinema-infra/src/main/java/com/cinema/infra/repository/TicketSeatRepository.java
  compose.yaml
  ddl.sql
  ddl_no_index.sql
  docs/data/create_dummy_data_cinema_250125.xlsx
  docs/images/corrected_erd2.png
  docs/images/corrected_erd3.png
  docs/images/nPlusOneSolved.png
  docs/images/problem3-3.png
  dummy_data.sql
  dummy_data_movie.sql
Labels: 3주차
